controller_list:
  - name: fake_lite6_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  # - name: fake_gripper_controller
  #   # action_ns: gripper_action
  #   # type: GripperCommand
  #   joints:
  #    - finger1_joint
  #    - finger2_joint
  #    - finger3_joint

# initial:
#   - group: lite6
#     pose:  home
