# joint_state_controller:
#   type: joint_state_controller/JointStateController
#   publish_rate: 125
  
controller_list:
  - name: "" # lite6_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  # - name: gripper_position_controller
  #   # action_ns: gripper_action
  #   # type: GripperCommand
  #   joints:
  #    - finger1_joint
    #  - finger2_joint
    #  - finger3_joint

# initial:
#   - group: lite6
#     pose:  home

